### ISSUE TITLE
OpenCV linking error 

### ISSUE THREAD

**Issue by glitzflitz** [walktree/libtorch-yolov3#23]
After executing make i get the following error. I'm using OpenCV4 on arch linux
```
[100%] Linking CXX executable yolo_app
/usr/bin/ld: CMakeFiles/yolo_app.dir/yolo_app.cpp.o: in function `main':
yolo_app.cpp:(.text+0x9f0): undefined reference to `cv::imread(std::string const&, int)'
/usr/bin/ld: yolo_app.cpp:(.text+0x137e): undefined reference to `cv::imwrite(std::string const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/yolo_app.dir/build.make:125: yolo_app] Error 1
make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/yolo_app.dir/all] Error 2
make: *** [Makefile:84: all] Error 2
```

**Comment by walktree** [comment]
Seems that openCV libs are not linked correctly, check your gcc version and Makefile please.

**Comment by glitzflitz** [comment]
Ok so I got it working by manually building libtorch from source but now its throwing segmentation error
```loading weight ...
weight loaded ...
start to inference ...
terminate called after throwing an instance of 'c10::Error'
  what():  Must not create a new variable from a variable, use its .tensor_data() (make_variable at /home/direwolf/Projects/pytorch/torch/include/torch/csrc/autograd/variable.h:542)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7fc1358e5b9a in /home/direwolf/Projects/pytorch/torch/lib/libc10.so)
frame #1: torch::autograd::make_variable(at::Tensor, bool, bool) + 0x10c (0x55be8013c765 in ./yolo-app)
frame #2: main + 0x66b (0x55be8013688d in ./yolo-app)
frame #3: __libc_start_main + 0xf3 (0x7fc1021beee3 in /usr/lib/libc.so.6)
frame #4: _start + 0x2e (0x55be801359be in ./yolo-app)
```

**Comment by mymultiverse** [comment]
> After executing make i get the following error. I'm using OpenCV4 on arch linux
> 
> ```
> [100%] Linking CXX executable yolo_app
> /usr/bin/ld: CMakeFiles/yolo_app.dir/yolo_app.cpp.o: in function `main':
> yolo_app.cpp:(.text+0x9f0): undefined reference to `cv::imread(std::string const&, int)'
> /usr/bin/ld: yolo_app.cpp:(.text+0x137e): undefined reference to `cv::imwrite(std::string const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
> collect2: error: ld returned 1 exit status
> make[2]: *** [CMakeFiles/yolo_app.dir/build.make:125: yolo_app] Error 1
> make[1]: *** [CMakeFiles/Makefile2:76: CMakeFiles/yolo_app.dir/all] Error 2
> make: *** [Makefile:84: all] Error 2
> ```
Indeed it is related to Open CV 
I had the exact same issue.  
I build OpenCV 4 from source by adding add_definitions(-D_GLIBCXX_USE_CXX11_ABI=0) to its CMakelists as proposed in the last comment of this issue which is active [here](https://github.com/opencv/opencv/issues/13000) and Then chnaged the C++ 14 to 11 in yolo CMakelists.  Now I am able to get the bounding box images. 
Hope this will help

**Comment by mymultiverse** [comment]
@GreyDireWolf 
Are you getting OpenCV shared object files with this:-
` ls /usr/local/lib/ -1
`
And also check this:-
`pkg-config --libs opencv
`

**Comment by glitzflitz** [comment]
@mymultiverse actually I solved the linking problem by building libtorch from source instead of downloading precompiled binaries. I guess the linking error was due to difference in ABI for precompiled libtorch and OpenCV on arch.

**Comment by bravestpeng** [comment]
in CMakeLists.txt
set(OpenCV_DIR "-----you open path------ /opencv/build")
find_package(OpenCV REQUIRED)
include_directories(${Opencv_INCLUDE_DIRSs})
link_directories(${Opencv_LIBRARIES_DIRSs})

**Comment by glitzflitz** [comment]
#23 Closed
