### ISSUE TITLE
Specified type of detection

### ISSUE THREAD

**Issue by zhanghongruiupup** [walktree/libtorch-yolov3#31]
thanks your work, it's great.
I just want to detect a specific kind of object and what to do.(For example, only people are tested.)
hope your reply,thanks

**Comment by walktree** [comment]
if (result_data[i][0] == 0)
{
   // person
}

**Comment by zhanghongruiupup** [comment]
> if (result_data[i][0] == 0)
> {
> // person
> }

I will try,Thank you again.

**Comment by zhanghongruiupup** [comment]
No matter what kind, result_data[i][0] == 0  .so can not only detect people.
hope your reply,thanks
