### ISSUE TITLE
OpenCV将图像加载为numpy数组，颜色通道顺序是BGR，PyTorch的图像通道顺序为RGB

### ISSUE THREAD

**Issue by tangxiongfei** [walktree/libtorch-yolov3#37]
https://github.com/walktree/libtorch-yolov3/blob/a32644ee3a13de607a5cb89e0e812850834399fd/main.cpp#L54

应该改为
cv::cvtColor(origin_image, resized_image,  cv::COLOR_BGR2RGB);

**Comment by walktree** [comment]
Yes, it should be a typo which included in a  submit.
