### ISSUE TITLE
crash in Darknet::load_weights() when load tiny weights

### ISSUE THREAD

**Issue by jjqcat** [walktree/libtorch-yolov3#4]
module_list.size() is 24

void Darknet::load_weights(const char *weight_file)
{
...
    for (int i = 0; i < module_list.size(); i++)
   {

   }
...
  conv_weights = conv_weights.view_as(conv_imp->weight);//------crah when i == 22
}

**Comment by walktree** [comment]
what version of libtorch you are using? v1.0.0 has been tested.

**Comment by jjqcat** [comment]
I also tested it with libtorch CPU  V1.0
