### ISSUE TITLE
支持最新的libtorch1.6版本

### ISSUE THREAD

**Issue by ouening** [walktree/libtorch-yolov3#52]
OS: Win 10 64
Libtorch: 1.6
Visual Studio 2017 (VC15)
OpenCV: 4.4 (win pre-build)
使用该库调用最新的libtorch的话会出现接口不兼容的问题，出现下面这些错误：

1. Darknet.cpp(18): error C2039: “isspace”: 不是“std”的成员

2. Darknet.cpp(139): error C2039: “with_bias”: 不是“torch::nn::ConvOptions<2>”的成员

3. Darknet.cpp(146): error C2039: “stateful”: 不是“torch::nn::BatchNormOptions

4. Darknet.cpp(380): error C2039: “BatchNorm”: 不是“torch::nn”的成员

5. Darknet.cpp(526): error C2039: “is_variable”: 不是“c10::TensorOptions”的成员

6. Darknet.cpp(550): error C2039: “BatchNormImpl”: 不是“torch::nn”的成员

相应的解决办法：
1. 添加头文件#include <typeinfo>
2. 将with_bias改为bias
![image](https://user-images.githubusercontent.com/15122811/91381634-75d7d080-e85a-11ea-8d40-f2de4f733a29.png)
3. 修改为track_running_stats:
![image](https://user-images.githubusercontent.com/15122811/91381683-9011ae80-e85a-11ea-9250-39f24bbf876d.png)
4. 修改为BathNorm2d
![image](https://user-images.githubusercontent.com/15122811/91381777-c0f1e380-e85a-11ea-91f6-b9a0e3b4c3d6.png)
5. 没找到对应的属性，直接注释了
![image](https://user-images.githubusercontent.com/15122811/91381815-d9fa9480-e85a-11ea-8aeb-b54c34be9477.png)
6. 修改为BatchNorm2dImpl：
![image](https://user-images.githubusercontent.com/15122811/91381796-cd763c00-e85a-11ea-819e-8f24e292e81e.png)

其实就是libtorch的接口还不稳定导致不同版本之间不兼容。
另外注意事项：
1. cmakelists.txt需要手动添加opencv地址
2. 64位框架编译：`cmake -G "Visual Studio 15 2017 Win64" -T host=x64 -DCMAKE_PREFIX_PATH="E:\MachineLearn
ing\libtorch" ..`
3. 运行程序的时候要复制libtorch的dll文件到执行路径

最后将修改后的程序托管在地址：[https://github.com/ouening/libtorch1.6-yolov3](https://github.com/ouening/libtorch1.6-yolov3)

**Comment by changanxiaofan** [comment]
thanks
